# Generated by Django 4.2.24 on 2025-11-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0157_alter_profile_timezone_mcqquestion_mcqoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='randomize_options',
            field=models.BooleanField(default=True, editable=False, help_text='Randomize the order of options for each user', verbose_name='randomize option order'),
        ),
    ]
