# Generated by Django 4.2.24 on 2025-11-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0158_alter_mcqquestion_randomize_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group/category of question', null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.problemgroup', verbose_name='question group'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='types',
            field=models.ManyToManyField(blank=True, help_text='The type of question, similar to problem types', to='judge.problemtype', verbose_name='question types'),
        ),
    ]
