# Generated by Django 4.2.24 on 2025-11-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0159_alter_mcqquestion_group_alter_mcqquestion_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestMCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='points')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_mcqs', to='judge.contest', verbose_name='contest')),
                ('mcq_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='judge.mcqquestion', verbose_name='MCQ question')),
            ],
            options={
                'verbose_name': 'contest MCQ question',
                'verbose_name_plural': 'contest MCQ questions',
                'ordering': ('order',),
                'unique_together': {('mcq_question', 'contest')},
            },
        ),
    ]
