# Generated by Django 4.2.23 on 2025-11-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0160_contestmcq'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mcqsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mcqsubmission',
            name='contest_object',
            field=models.ForeignKey(blank=True, help_text='Contest MCQ this submission belongs to (if in contest)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='judge.contestmcq', verbose_name='contest MCQ'),
        ),
        migrations.AddField(
            model_name='mcqsubmission',
            name='participation',
            field=models.ForeignKey(blank=True, help_text='Contest participation this submission belongs to (if in contest)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_submissions', to='judge.contestparticipation', verbose_name='contest participation'),
        ),
    ]
