# Generated by Django 4.2.23 on 2025-11-08 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0161_alter_mcqsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestMCQResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0, verbose_name='total questions')),
                ('attempted', models.IntegerField(default=0, verbose_name='attempted')),
                ('correct', models.IntegerField(default=0, verbose_name='correct')),
                ('wrong', models.IntegerField(default=0, verbose_name='wrong')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='score')),
                ('is_final', models.BooleanField(default=False, help_text='True when user submits or time expires', verbose_name='is final submission')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='calculated at')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_results', to='judge.contest', verbose_name='contest')),
                ('participation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_result', to='judge.contestparticipation', verbose_name='participation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_contest_results', to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'contest MCQ result',
                'verbose_name_plural': 'contest MCQ results',
                'ordering': ('-score', '-submitted_at'),
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
